
name = "your_project_name"
compiler = "gcc"		# can optionally use full path
version = ""
#-O
optimize = "off"

binpath = "build/"

srcfiles = [
]

# -D
defines = [
]

# -I
includedirs = [
]

# -L
libdirs = [
]

# -l
libfiles = [
]

# -W
warnings = [
]