
name = "test"
compiler = "gcc"		# can optionally use full path
version = ""
#-O
optimize = "off"

binpath = "build/test/bin"

srcfiles = [
	"src/graphics/gui.cpp",
]

# -D
defines = [
	"_CRT_SECURE_NO_WARNINGS",
]

# -I
includedirs = [
	"vendor/glad/include",
	"vendor/SDL/include",
	"vendor/STB_IMAGE/include",
	"vendor/Fastor/",
	"vendor/Fastor/Fastor",
	"vendor/NumCpp/include/",
	"vendor/Nuklear",
	"vendor/Nuklear/demo/common"
]

# -L
libdirs = [
	"vendor/SDL/lib",
]

# -l
libfiles = [
	"SDL2main",
	"SDL2",
	"opengl32",
]

# -W
warnings = [
	'no-narrowing'
]
