name      = "App"
compiler  = "clang++"
version   = "c++17"

#-O
#optimize = "off"
optimize = "off"

#debug = "on"
debug = "off"

binpath = "build/"

srcfiles = [
	"src/*"
]

# -D
defines = [
	"_CRT_SECURE_NO_WARNINGS",
]

# -I
includedirs = [
  "src/", 
  "vendor/", 
]

# -L
libdirs = [
]

# -l
libfiles = [
  #"user32",
  #"gdi32"
]

# -W
warnings = [
]